/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pGUI;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pcode.Dbconnect;

/**
 *
 * @author Sachin
 */
public class ChangePassword extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public ChangePassword() {
         initComponents();
         con = Dbconnect.dconnect();
         this.getContentPane().setBackground(Color.black);
         this.setResizable(false);
         id_txt.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closxo = new javax.swing.JLabel();
        minixo = new javax.swing.JLabel();
        gragMetohell = new javax.swing.JLabel();
        jButton1 = new javax.swing.JLabel();
        hoverBar = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        opass_txt = new javax.swing.JPasswordField();
        npass_txt = new javax.swing.JPasswordField();
        cpass_txt = new javax.swing.JPasswordField();
        backtrack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(398, 462));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closxo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closxoMouseClicked(evt);
            }
        });
        getContentPane().add(closxo, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 14, 35, 35));

        minixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minixoMouseClicked(evt);
            }
        });
        getContentPane().add(minixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 14, 35, 35));

        gragMetohell.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                gragMetohellMouseDragged(evt);
            }
        });
        gragMetohell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gragMetohellMousePressed(evt);
            }
        });
        getContentPane().add(gragMetohell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pGUI/pass1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 178, 40));

        hoverBar.setForeground(new java.awt.Color(255, 255, 255));
        hoverBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hoverBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 424, 310, 20));

        id_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_txt.setBorder(null);
        id_txt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                id_txtMouseMoved(evt);
            }
        });
        id_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_txtKeyPressed(evt);
            }
        });
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 123, 140, 20));

        opass_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        opass_txt.setBorder(null);
        opass_txt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                opass_txtMouseMoved(evt);
            }
        });
        opass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opass_txtKeyPressed(evt);
            }
        });
        getContentPane().add(opass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 174, 140, 20));

        npass_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        npass_txt.setBorder(null);
        npass_txt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                npass_txtMouseMoved(evt);
            }
        });
        npass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                npass_txtKeyPressed(evt);
            }
        });
        getContentPane().add(npass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 224, 140, 20));

        cpass_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpass_txt.setBorder(null);
        cpass_txt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cpass_txtMouseMoved(evt);
            }
        });
        cpass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpass_txtKeyPressed(evt);
            }
        });
        getContentPane().add(cpass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 276, 140, 20));

        backtrack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employeePass.png"))); // NOI18N
        backtrack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backtrackMouseMoved(evt);
            }
        });
        getContentPane().add(backtrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, 462));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closxoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closxoMouseClicked
       dispose();
    }//GEN-LAST:event_closxoMouseClicked

    private void minixoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minixoMouseClicked
        this.setState(leaveBookingView.ICONIFIED);
    }//GEN-LAST:event_minixoMouseClicked

    private void gragMetohellMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gragMetohellMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_gragMetohellMouseDragged

    private void gragMetohellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gragMetohellMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_gragMetohellMousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
             int c = JOptionPane.showConfirmDialog(null,"Do you want to Change Password ?");
        
        if(c==0){
        
        String id = id_txt.getText();
        String opass = opass_txt.getText();
        String npass = npass_txt.getText();
        String cpass = cpass_txt.getText();
        
        if(npass.equals(cpass)){
            
            try {
                String sql = "select * from employee_details where emp_ID = ? && password =? ";
                
                pst = con.prepareStatement(sql);
                pst.setString(1,id_txt.getText() );
                pst.setString(2,opass_txt.getText() );
                rs = pst.executeQuery();
                opass_txt.setText("");
                
                if(rs.next()){
                
                    String sql2 ="update employee_details set password ='"+npass+"' where emp_ID = '"+id+"'  ";
                    
                    pst = con.prepareStatement(sql2);
                    pst.execute();
            
                    JOptionPane.showMessageDialog(null,"Successfully Updated");
                }
                else{
 
                    JOptionPane.showMessageDialog(null,"UserName or Password Invalid");

                } 
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
        
            JOptionPane.showMessageDialog(null,"Confirm password is wrong");
        }
        
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
       ImageIcon II = new ImageIcon(getClass().getResource("pass2.png"));
       jButton1.setIcon(II);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
       ImageIcon II = new ImageIcon(getClass().getResource("pass1.png"));
       jButton1.setIcon(II);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("pass3.png"));
       jButton1.setIcon(II);
    }//GEN-LAST:event_jButton1MousePressed

    private void opass_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opass_txtKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           npass_txt.grabFocus();
       }
    }//GEN-LAST:event_opass_txtKeyPressed

    private void npass_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npass_txtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           cpass_txt.grabFocus();
       }
    }//GEN-LAST:event_npass_txtKeyPressed

    private void cpass_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpass_txtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                       int c = JOptionPane.showConfirmDialog(null,"Do you want to Change Password ?");
        
        if(c==0){
        
        String id = id_txt.getText();
        String opass = opass_txt.getText();
        String npass = npass_txt.getText();
        String cpass = cpass_txt.getText();
        
        if(npass.equals(cpass)){
            
            try {
                String sql = "select * from employee_details where emp_ID = ? && password =? ";
                
                pst = con.prepareStatement(sql);
                pst.setString(1,id_txt.getText() );
                pst.setString(2,opass_txt.getText() );
                rs = pst.executeQuery();
                opass_txt.setText("");
                
                if(rs.next()){
                
                    String sql2 ="update employee_details set password ='"+npass+"' where emp_ID = '"+id+"'  ";
                    
                    pst = con.prepareStatement(sql2);
                    pst.execute();
            
                    JOptionPane.showMessageDialog(null,"Successfully Updated");
                }
                else{
 
                    JOptionPane.showMessageDialog(null,"UserName or Password Invalid");

                } 
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
        
            JOptionPane.showMessageDialog(null,"Confirm password is wrong");
        }
        
        }
       }
    }//GEN-LAST:event_cpass_txtKeyPressed

    private void opass_txtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opass_txtMouseMoved
        hoverBar.setText("Enter Current Password");
    }//GEN-LAST:event_opass_txtMouseMoved

    private void npass_txtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_npass_txtMouseMoved
       hoverBar.setText("Enter New Password");
    }//GEN-LAST:event_npass_txtMouseMoved

    private void cpass_txtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpass_txtMouseMoved
       hoverBar.setText("Confirm your New Password");
    }//GEN-LAST:event_cpass_txtMouseMoved

    private void backtrackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtrackMouseMoved
       hoverBar.setText(" ");
    }//GEN-LAST:event_backtrackMouseMoved

    private void id_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_txtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           opass_txt.grabFocus();
       }
    }//GEN-LAST:event_id_txtKeyPressed

    private void id_txtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_txtMouseMoved
        hoverBar.setText("Enter Your ID");
    }//GEN-LAST:event_id_txtMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backtrack;
    private javax.swing.JLabel closxo;
    private javax.swing.JPasswordField cpass_txt;
    private javax.swing.JLabel gragMetohell;
    private javax.swing.JLabel hoverBar;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jButton1;
    private javax.swing.JLabel minixo;
    private javax.swing.JPasswordField npass_txt;
    private javax.swing.JPasswordField opass_txt;
    // End of variables declaration//GEN-END:variables
}
