/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pGUI;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import pcode.Dbconnect;

/**
 *
 * @author Sachin
 */
public class Report extends javax.swing.JFrame {
     Connection con = null;
     int xMouse;
     int yMouse;
    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        this.setDefaultCloseOperation (Report.DISPOSE_ON_CLOSE );
        this.getContentPane().setBackground(Color.WHITE);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drag = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        employee = new javax.swing.JLabel();
        attendance = new javax.swing.JLabel();
        stdt_txt = new com.toedter.calendar.JDateChooser();
        endt_txt = new com.toedter.calendar.JDateChooser();
        to = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        hoverBar = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        backLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, 20));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 20, 35, 35));

        employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pGUI/btnEmp3.png"))); // NOI18N
        employee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                employeeMouseMoved(evt);
            }
        });
        employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employeeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                employeeMouseReleased(evt);
            }
        });
        getContentPane().add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 228, 45));

        attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pGUI/attendancex3.png"))); // NOI18N
        attendance.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                attendanceMouseMoved(evt);
            }
        });
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attendanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                attendanceMouseReleased(evt);
            }
        });
        getContentPane().add(attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 228, 45));

        stdt_txt.setDateFormatString("yyyy-MM-dd");
        stdt_txt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                stdt_txtMouseMoved(evt);
            }
        });
        getContentPane().add(stdt_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 154, 140, 24));

        endt_txt.setDateFormatString("yyyy-MM-dd");
        endt_txt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                endt_txtMouseMoved(evt);
            }
        });
        getContentPane().add(endt_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 218, 140, 24));

        to.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                toMouseMoved(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 170, 40));

        from.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fromMouseMoved(evt);
            }
        });
        getContentPane().add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, 30));

        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });
        getContentPane().add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 20, 35, 35));

        hoverBar.setForeground(new java.awt.Color(255, 255, 255));
        hoverBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hoverBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 428, 320, 20));

        id_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_txt.setBorder(null);
        id_txt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                id_txtMouseMoved(evt);
            }
        });
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 100, 140, 20));

        backLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reportx.png"))); // NOI18N
        backLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backLblMouseMoved(evt);
            }
        });
        getContentPane().add(backLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, 462));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_miniMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_dragMouseDragged

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void id_txtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_txtMouseMoved
        hoverBar.setText("Enter Employee ID");
        id_txt.grabFocus();
    }//GEN-LAST:event_id_txtMouseMoved

    private void stdt_txtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdt_txtMouseMoved
       hoverBar.setText("Enter Start Date");
    }//GEN-LAST:event_stdt_txtMouseMoved

    private void toMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toMouseMoved
       hoverBar.setText("Enter End Date");
    }//GEN-LAST:event_toMouseMoved

    private void fromMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fromMouseMoved
       hoverBar.setText("Enter Start Date");
    }//GEN-LAST:event_fromMouseMoved

    private void endt_txtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endt_txtMouseMoved
       hoverBar.setText("Enter End Date");
    }//GEN-LAST:event_endt_txtMouseMoved

    private void backLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLblMouseMoved
       hoverBar.setText(" ");
    }//GEN-LAST:event_backLblMouseMoved

    private void attendanceMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseMoved
       hoverBar.setText("Generate an Attendance Report");
    }//GEN-LAST:event_attendanceMouseMoved

    private void employeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseMoved
        hoverBar.setText("Generate an Employee Detail Report");
    }//GEN-LAST:event_employeeMouseMoved

    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
      
    }//GEN-LAST:event_attendanceMouseClicked

    private void attendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("attendancex1.png"));
        attendance.setIcon(II);
    }//GEN-LAST:event_attendanceMouseEntered

    private void attendanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("attendancex2.png"));
        attendance.setIcon(II);
    }//GEN-LAST:event_attendanceMousePressed

    private void attendanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("attendancex1.png"));
        attendance.setIcon(II);
    }//GEN-LAST:event_attendanceMouseReleased

    private void attendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("attendancex3.png"));
        attendance.setIcon(II);
    }//GEN-LAST:event_attendanceMouseExited

    private void employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseClicked
      
    }//GEN-LAST:event_employeeMouseClicked

    private void employeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("btnEmpx1.png"));
        employee.setIcon(II);
    }//GEN-LAST:event_employeeMouseEntered

    private void employeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("btnEmpx3.png"));
        employee.setIcon(II);
    }//GEN-LAST:event_employeeMouseExited

    private void employeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("btnEmpx2.png"));
        employee.setIcon(II);
    }//GEN-LAST:event_employeeMousePressed

    private void employeeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("btnEmpx1.png"));
        employee.setIcon(II);
    }//GEN-LAST:event_employeeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel backLbl;
    private javax.swing.JLabel close;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel employee;
    private com.toedter.calendar.JDateChooser endt_txt;
    private javax.swing.JLabel from;
    private javax.swing.JLabel hoverBar;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel mini;
    private com.toedter.calendar.JDateChooser stdt_txt;
    private javax.swing.JLabel to;
    // End of variables declaration//GEN-END:variables
}
